Consultas = [
    {
    'id': '001',
    'nome_paciente': 'Maria Silva',
    'cpf_paciente':'123.456.789-00',
    'nome_medico':'Dr. Joao da Silva',
    'especialidade_medico':'Cardiologia',
    'data_consulta':'2026-10-10',
    'hora_consulta':'09:00',
    'convenio':'Unimed',
    'status':'Agendada',
    },
    {
    'id': '002',
    'nome_paciente': 'Roberto Mendonca',
    'cpf_paciente':'987.654.321-00',
    'nome_medico':'Dr. Ana Paula',
    'especialidade_medico':'Fisioterapia',
    'data_consulta':'2026-10-11',
    'hora_consulta':'07:30',
    'convenio':'Nossa Saude',
    'status':'Agendada',
    },
    {
    'id': '003',
    'nome_paciente': 'Rodrigo Lima',
    'cpf_paciente':'321.654.987-00',
    'nome_medico':'Dr. Carlos Souza',
    'especialidade_medico':'Ortopedia',
    'data_consulta':'2026-10-12',
    'hora_consulta':'14:00',
    'convenio':'Sul America',
    'status':'Pendente',
    },
    {
    'id': '004',
    'nome_paciente': 'Agatha Oliveira',
    'cpf_paciente':'456.789.123-00',
    'nome_medico':'Dr. Maria Santos',
    'especialidade_medico':'Dermatologia',
    'data_consulta':'2026-10-13',
    'hora_consulta':'11:00',
    'convenio':'Bradesco Saude',
    'status':'Agendada',
    },
    {
    'id': '005',
    'nome_paciente': 'Oliver Costa',
    'cpf_paciente':'255.635.787-00',
    'nome_medico':'Dr. Pedro Alves',
    'especialidade_medico':'Psiquiatria',
    'data_consulta':'2026-10-14',
    'hora_consulta':'10:30',
    'convenio':'Unimed',
    'status':'Pendente',
    }
]